### ISSUE TITLE
error when trying to play movie

### ISSUE THREAD

**Issue by rodrigomendoza** [markop159/KODI-Popcorn-Time#109]
error in log:
2019-08-03 17:13:18.134 T:1318040288 WARNING: CPythonInvoker(27, /home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
2019-08-03 17:13:31.683 T:1574957792   FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 40, in <module>
                                                getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/player.py", line 106, in show
                                                TorrentPlayer().playTorrentFile(self.mediaSettings, build_magnetFromMeta(params[quality], "quality %s" %quality), item, subtitle)
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 432, in playTorrentFile
                                                raise Abort()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 42, in __exit__
                                                self.close()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 379, in close
                                                super(Loader, self).close()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                self.raiseAnyError()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 22, in ___run
                                                self._target()
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 257, in _run
                                                if self._TEngine.start() and self._getPlayFile() and self._checkData() and self._preloading(self._item.get('stream_info', {}).get('video', {}).get('duration', 0)):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 116, in start
                                                raise TorrentError("Can't start torrent2http: %s" % str(sys.exc_info()[1]))
                                            TorrentError: Can't start torrent2http: [Errno 12] Cannot allocate memory

**Comment by markop159** [comment]
can you try this version:
[https://github.com/markop159/KODI-Popcorn-Time/tree/fast_experimental](https://github.com/markop159/KODI-Popcorn-Time/tree/fast_experimental)

This is a beta version, it is a little bit faster (in loading tv shows) than normal version and have some fixes (also have some more minor bugs).

For me on OSMC is working OK, on Windows sometimes crashes.

If it is still not working can you add bigger log with [debug logging](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs) enabled.
