### ISSUE TITLE
FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):

### ISSUE THREAD

**Issue by scalpmonkey** [markop159/KODI-Popcorn-Time#77]
Here is part of the log concerning kodipopcorntime

`14:03:02.041 T:1709544352   FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 40, in <module>
                                                getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/player.py", line 108, in show
                                                TorrentPlayer().playTorrentFile(self.mediaSettings, build_magnetFromMeta(params[quality], "quality %s" %quality), item, subtitle)
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 432, in playTorrentFile
                                                raise Abort()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 42, in __exit__
                                                self.close()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 379, in close
                                                super(Loader, self).close()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                self.raiseAnyError()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 22, in ___run
                                                self._target()
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 257, in _run
                                                if self._TEngine.start() and self._getPlayFile() and self._checkData() and self._preloading(self._item.get('stream_info', {}).get('video', {}).get('duration', 0)):
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 279, in _getPlayFile
                                                if self._TEngine.playFile(1):
                                              File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 169, in playFile
                                                urllib2.urlopen(f['url'], timeout=50)`

**Comment by markop159** [comment]
Can you add more info? Kodi version, os, plugin version and the steps to reproduce issue.

And full debug log would be helpfull.

**Comment by markop159** [comment]
No answer, closing issue.
